### ISSUE TITLE
How did you visualize the notes?

### ISSUE THREAD

**Issue by mr-kaynak** [FRC4561TerrorBytes/TB2024#17]
I'm trying to make the real shooter in your video on YouTube, where does the note visualizer come from, how do you provide it, will the custom assets folder of your robot be added to github, thank you very much for providing support.

**Comment by ethanprivette** [comment]
The note visualizer is in the code already, it should show up in advantage scope once you run a shoot command. As for the robot folder, it should be in the mechanism-sim branch now.

**Comment by mr-kaynak** [comment]
I found the shooter codes, but for information purposes, shooter is missing in your main code.
